.Dd 2023
.Dt PB 5
.
.Sh NAME
.Nm pb
.Nd the command line puzzle box
.
.Sh DESCRIPTION
That is it for now! This is will sit here until more stages are added!

.Sh OPTIONS
.Nm --help -h
.Nd print out the command line help

.Nm --hint
.Nd print out a stage specific hint

.Nm --reset
.Nd reset your progress to the beginning in case you want this madness again.

.Nm --artifacts
.Nd print out a list of the artifacts that this puzzle box has created for
    clean up in case you're worried. Example: pb --artifacts | xargs rf --rf
